version: "3.9"
services:
  berloga_postgres:
    image: postgres:13.3
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_PASSWORD: ${PASS}
      PGDATA: ${PGDATA}
    volumes:
      - ${VOLUME_ENTRY}
      - ${VOLUME_DATA}
    ports:
      - ${PORT}:5432
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G